default_settings: null
behaviors:
  FinalProject_Maze:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      gail:
        gamma: 0.99
        strength: 0.09
        demo_path: C:\Users\chtou\Desktop\Grad Studies\Fall 2021\Special topics in AI (AI in games)\final project\finalproject\Assets\AIG-Works\FinalProject\Demonstration\MazeDemo.demo
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 1000000
    max_steps: 8000000
    time_horizon: 128
    summary_freq: 200000